apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-mysql
  name: service-mysql
spec:
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app: service-mysql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: service-mysql
    spec:
      containers:
        - image: service-mysql
          imagePullPolicy: "Always"
          name: service-mysql
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 1024Mi
          volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: service-mysql-properties
      imagePullSecrets:
        - name: ocir-secret